version: '3.8'

services:
  discovery-service:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka

  coefficient-service:
    build:
      context: ./coefficient-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - discovery-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka

  roots-service:
    build:
      context: ./roots-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - discovery-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka

  factorization-service:
    build:
      context: ./factorization-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - discovery-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka

  polynomial-api:
    build:
      context: ./polynomial-api
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - discovery-service
      - coefficient-service
      - roots-service
      - factorization-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
  react-app:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    depends_on:
      - polynomial-api
